_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.10.5
        t:
            "1":
                - 55
            "2":
                - 55
            "3":
                - 23
                - 55
            "4": 3.10.5
            "5": 0.19.11
            "8":
                - 2
                - 5
            "12": 0.19.11
            "13": darwin-arm64
