_current_progress_remaining:
    value: 1
_custom_logger:
    value: "False"
_episode_num:
    value: 0
_last_episode_starts:
    value: '[ True]'
_last_obs:
    value: |-
        [[[ 0.          0.          0.1125      0.         -0.
            0.          0.          0.          0.          0.
            0.          0.          1.          1.          1.
            0.1588      0.1588      0.          0.22457711  0.3176
            0.3176      0.          0.44915423  0.4764      0.4764
            0.          0.6737313   0.          0.          0.        ]
          [ 0.1588      0.1588      0.1125      0.         -0.
            0.          0.          0.          0.          0.
            0.          0.          1.          1.          1.
           -0.1588     -0.1588      0.          0.22457711  0.1588
            0.1588      0.          0.22457711  0.3176      0.3176
            0.          0.44915423  0.          0.          0.        ]
          [ 0.3176      0.3176      0.1125      0.         -0.
            0.          0.          0.          0.          0.
            0.          0.          1.          1.          1.
           -0.3176     -0.3176      0.          0.44915423 -0.1588
           -0.1588      0.          0.22457711  0.1588      0.1588
            0.          0.22457711  0.          0.          0.        ]
          [ 0.4764      0.4764      0.1125      0.         -0.
            0.          0.          0.          0.          0.
            0.          0.          1.          1.          1.
           -0.4764     -0.4764      0.          0.6737313  -0.3176
           -0.3176      0.          0.44915423 -0.1588     -0.1588
            0.          0.22457711  0.          0.          0.        ]]]
_last_original_obs:
    value: None
_logger:
    value: <stable_baselines3.common.logger.Logger object at 0x3222be860>
_n_updates:
    value: 0
_num_timesteps_at_start:
    value: 0
_stats_window_size:
    value: 100
_total_timesteps:
    value: 500000
_vec_normalize_env:
    value: None
_wandb:
    value:
        cli_version: 0.19.11
        code_path: code/gym_pybullet_drones/examples/learn_multi.py
        m: []
        python_version: 3.10.5
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 1
                - 3
                - 13
                - 16
                - 22
                - 23
                - 35
                - 55
                - 61
                - 62
            "4": 3.10.5
            "5": 0.19.11
            "8":
                - 2
                - 5
            "12": 0.19.11
            "13": darwin-arm64
act_type:
    value: RPM
action_noise:
    value: None
action_space:
    value: Box(-1.0, 1.0, (4, 4), float32)
algo:
    value: PPO
architecture:
    value: MultiAgent
batch_size:
    value: 128
clip_range:
    value: 0.2
clip_range_vf:
    value: None
device:
    value: cpu
duration_sec:
    value: 3
ent_coef:
    value: 0.01
env:
    value: <stable_baselines3.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x16f11a260>
ep_info_buffer:
    value: deque([], maxlen=100)
ep_success_buffer:
    value: deque([], maxlen=100)
eval_freq:
    value: 25000
extractor_type:
    value: attention
features_dim:
    value: 32
gae_lambda:
    value: 0.95
gamma:
    value: 0.99
learning_rate:
    value: 0.0003
log_freq:
    value: 1000
lr_schedule:
    value: <function get_schedule_fn.<locals>.<lambda> at 0x16def0b80>
max_grad_norm:
    value: 0.5
n_envs:
    value: 1
n_epochs:
    value: 10
n_steps:
    value: 2048
normalize_advantage:
    value: "True"
num_drones:
    value: 4
num_timesteps:
    value: 0
obs_type:
    value: KIN
observation_space:
    value: |-
        Box([[-inf -inf   0. -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf
          -inf -inf -inf -inf   0. -inf -inf -inf   0. -inf -inf -inf   0. -inf
          -inf -inf]
         [-inf -inf   0. -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf
          -inf -inf -inf -inf   0. -inf -inf -inf   0. -inf -inf -inf   0. -inf
          -inf -inf]
         [-inf -inf   0. -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf
          -inf -inf -inf -inf   0. -inf -inf -inf   0. -inf -inf -inf   0. -inf
          -inf -inf]
         [-inf -inf   0. -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf
          -inf -inf -inf -inf   0. -inf -inf -inf   0. -inf -inf -inf   0. -inf
          -inf -inf]], inf, (4, 30), float32)
policy:
    value: |-
        ActorCriticPolicy(
          (features_extractor): MultiAgentSelfAttentionExtractor(
            (agent_encoder): Sequential(
              (0): Linear(in_features=30, out_features=128, bias=True)
              (1): ReLU()
              (2): Linear(in_features=128, out_features=128, bias=True)
              (3): ReLU()
              (4): Linear(in_features=128, out_features=64, bias=True)
              (5): ReLU()
            )
            (query_proj): Linear(in_features=64, out_features=64, bias=True)
            (key_proj): Linear(in_features=64, out_features=64, bias=True)
            (value_proj): Linear(in_features=64, out_features=64, bias=True)
            (aggregator): Sequential(
              (0): Linear(in_features=256, out_features=32, bias=True)
              (1): ReLU()
              (2): Linear(in_features=32, out_features=32, bias=True)
              (3): ReLU()
            )
          )
          (pi_features_extractor): MultiAgentSelfAttentionExtractor(
            (agent_encoder): Sequential(
              (0): Linear(in_features=30, out_features=128, bias=True)
              (1): ReLU()
              (2): Linear(in_features=128, out_features=128, bias=True)
              (3): ReLU()
              (4): Linear(in_features=128, out_features=64, bias=True)
              (5): ReLU()
            )
            (query_proj): Linear(in_features=64, out_features=64, bias=True)
            (key_proj): Linear(in_features=64, out_features=64, bias=True)
            (value_proj): Linear(in_features=64, out_features=64, bias=True)
            (aggregator): Sequential(
              (0): Linear(in_features=256, out_features=32, bias=True)
              (1): ReLU()
              (2): Linear(in_features=32, out_features=32, bias=True)
              (3): ReLU()
            )
          )
          (vf_features_extractor): MultiAgentSelfAttentionExtractor(
            (agent_encoder): Sequential(
              (0): Linear(in_features=30, out_features=128, bias=True)
              (1): ReLU()
              (2): Linear(in_features=128, out_features=128, bias=True)
              (3): ReLU()
              (4): Linear(in_features=128, out_features=64, bias=True)
              (5): ReLU()
            )
            (query_proj): Linear(in_features=64, out_features=64, bias=True)
            (key_proj): Linear(in_features=64, out_features=64, bias=True)
            (value_proj): Linear(in_features=64, out_features=64, bias=True)
            (aggregator): Sequential(
              (0): Linear(in_features=256, out_features=32, bias=True)
              (1): ReLU()
              (2): Linear(in_features=32, out_features=32, bias=True)
              (3): ReLU()
            )
          )
          (mlp_extractor): MlpExtractor(
            (policy_net): Sequential(
              (0): Linear(in_features=32, out_features=64, bias=True)
              (1): Tanh()
              (2): Linear(in_features=64, out_features=64, bias=True)
              (3): Tanh()
            )
            (value_net): Sequential(
              (0): Linear(in_features=32, out_features=64, bias=True)
              (1): Tanh()
              (2): Linear(in_features=64, out_features=64, bias=True)
              (3): Tanh()
            )
          )
          (action_net): Linear(in_features=64, out_features=16, bias=True)
          (value_net): Linear(in_features=64, out_features=1, bias=True)
        )
policy_class:
    value: <class 'stable_baselines3.common.policies.ActorCriticPolicy'>
policy_kwargs:
    value: '{''features_extractor_class'': <class ''multi_agent_extractors.MultiAgentSelfAttentionExtractor''>, ''features_extractor_kwargs'': {''features_dim'': 32}}'
rollout_buffer:
    value: <stable_baselines3.common.buffers.RolloutBuffer object at 0x16deef2b0>
rollout_buffer_class:
    value: <class 'stable_baselines3.common.buffers.RolloutBuffer'>
rollout_buffer_kwargs:
    value: '{}'
save_freq_evals:
    value: 1
sde_sample_freq:
    value: -1
seed:
    value: None
start_time:
    value: 1748329798244651000
target_kl:
    value: None
tensorboard_log:
    value: results/multiagent_attention_swarm_20250527_100955/tb
total_timesteps:
    value: 500000
use_sde:
    value: "False"
verbose:
    value: 1
vf_coef:
    value: 0.5
