_wandb:
    value:
        cli_version: 0.19.11
        code_path: code/gym_pybullet_drones/examples/train_rllib_multi_drone.py
        m: []
        python_version: 3.10.5
        t:
            "1":
                - 1
                - 30
                - 55
            "2":
                - 1
                - 30
                - 55
            "3":
                - 13
                - 15
                - 16
                - 23
                - 55
            "4": 3.10.5
            "5": 0.19.11
            "8":
                - 2
                - 5
            "12": 0.19.11
            "13": darwin-arm64
act_type:
    value: RPM
checkpoint_freq:
    value: 50
clip_param:
    value: 0.15
dropout_rate:
    value: 0.05
entropy_coeff:
    value: 0.008
evaluation_interval:
    value: 25
gamma:
    value: 0.99
grad_clip:
    value: 0.5
hidden_dim:
    value: 256
keep_checkpoints_num:
    value: 5
kl_coeff:
    value: 0.2
kl_target:
    value: 0.01
lambda_:
    value: 0.95
log_level:
    value: INFO
lr:
    value: 8e-05
model_type:
    value: shared
num_cpus_per_worker:
    value: 1
num_drones:
    value: 4
num_envs_per_worker:
    value: 1
num_gpus:
    value: 1
num_sgd_iter:
    value: 10
num_workers:
    value: 8
obs_type:
    value: KIN
reward_params:
    value:
        bounds_penalty: 12
        crash_penalty: 20
        lambda_1: 25
        lambda_2: 2
        lambda_3: 0.5
        lambda_4: 0.008
        lambda_5: 0.12
rollout_fragment_length:
    value: 512
sgd_minibatch_size:
    value: 1024
steps_per_target:
    value: 100
target_scale:
    value: 1.2
total_timesteps:
    value: 5000000
train_batch_size:
    value: 16384
use_attention:
    value: false
use_layer_norm:
    value: true
vf_loss_coeff:
    value: 0.5
wandb_entity:
    value: null
wandb_project:
    value: rllib-drone-swarm
