_wandb:
    value:
        cli_version: 0.19.11
        code_path: code/gym_pybullet_drones/examples/train_multi_td3.py
        m: []
        python_version: 3.10.5
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 13
                - 15
                - 16
                - 23
                - 35
                - 55
            "4": 3.10.5
            "5": 0.19.11
            "8":
                - 2
                - 5
            "12": 0.19.11
            "13": darwin-arm64
act_type:
    value: RPM
adaptive_difficulty:
    value: true
algorithm:
    value: ppo
batch_size:
    value: 64
clip_range:
    value: 0.2
ent_coef:
    value: 0.01
episode_length_sec:
    value: 3
eval_freq:
    value: 25000
extractor_type:
    value: matrix
features_dim:
    value: 128
gae_lambda:
    value: 0.95
gamma:
    value: 0.99
learning_rate:
    value: 0.0003
n_epochs:
    value: 10
n_eval_episodes:
    value: 5
n_steps:
    value: 2048
noise_std:
    value: 0.1
noise_type:
    value: normal
normalize_observations:
    value: false
num_drones:
    value: 1
num_vec_envs:
    value: 4
obs_type:
    value: KIN
total_timesteps:
    value: 2000000
