_wandb:
    value:
        cli_version: 0.19.11
        code_path: code/gym_pybullet_drones/examples/learn_multi.py
        m: []
        python_version: 3.10.5
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 13
                - 15
                - 16
                - 23
                - 35
                - 55
            "4": 3.10.5
            "5": 0.19.11
            "8":
                - 2
                - 5
            "12": 0.19.11
            "13": darwin-arm64
act_type:
    value: RPM
algo:
    value: PPO
architecture:
    value: MultiAgent_Matrix
batch_size:
    value: 1024
clip_range:
    value: 0.15
duration_sec:
    value: 3
ent_coef:
    value: 0.001
eval_freq:
    value: 25000
extractor_type:
    value: matrix
features_dim:
    value: 16
gae_lambda:
    value: 0.95
gamma:
    value: 0.99
learning_rate:
    value: 0.0003
log_freq:
    value: 500
min_reward_improvement:
    value: 5
n_epochs:
    value: 5
n_steps:
    value: 2048
num_drones:
    value: 1
obs_type:
    value: KIN
paper_reward_hyperparameters:
    value:
        lambda_1: 200
        lambda_2: 1.5
        lambda_3: 0.4
        lambda_4: 0.001
        lambda_5: 0.001
reward_function:
    value: paper_based
save_freq:
    value: 25000
total_timesteps:
    value: 2000000
