_wandb:
    value:
        cli_version: 0.19.11
        code_path: code/gym_pybullet_drones/examples/learn_multi.py
        m: []
        python_version: 3.10.5
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 13
                - 15
                - 16
                - 23
                - 35
                - 55
            "4": 3.10.5
            "5": 0.19.11
            "8":
                - 2
                - 5
            "12": 0.19.11
            "13": darwin-arm64
act_type:
    value: PID
algo:
    value: PPO
architecture:
    value: MultiAgent_Matrix
batch_size:
    value: 128
clip_range:
    value: 0.2
duration_sec:
    value: 3
ent_coef:
    value: 0.01
eval_freq:
    value: 6250
extractor_type:
    value: matrix
features_dim:
    value: 32
gae_lambda:
    value: 0.95
gamma:
    value: 0.99
learning_rate:
    value: 0.0003
log_freq:
    value: 1000
min_reward_improvement:
    value: 1
n_epochs:
    value: 10
n_steps:
    value: 2048
num_drones:
    value: 1
obs_type:
    value: KIN
save_freq:
    value: 25000
total_timesteps:
    value: 1900000
