_current_progress_remaining:
    value: 1
_custom_logger:
    value: "False"
_episode_num:
    value: 0
_last_episode_starts:
    value: '[ True]'
_last_obs:
    value: |-
        [[[ 0.         0.         0.1125     0.        -0.         0.
            0.         0.         0.         0.         0.         0.
            0.         0.         0.         0.         0.         0.
            0.         0.         0.         0.         0.         0.
            0.         0.         0.         0.         0.         0.
            0.         0.         0.         0.         0.         0.
            0.         0.         0.         0.         0.         0.
            0.         0.         0.         0.         0.         0.
            0.         0.         0.         0.         0.         0.
            0.         0.         0.         1.         1.         1.
            1.         1.         0.8875     1.6696275  0.       ]
          [ 0.1588     0.1588     0.1125     0.        -0.         0.
            0.         0.         0.         0.         0.         0.
            0.         0.         0.         0.         0.         0.
            0.         0.         0.         0.         0.         0.
            0.         0.         0.         0.         0.         0.
            0.         0.         0.         0.         0.         0.
            0.         0.         0.         0.         0.         0.
            0.         0.         0.         0.         0.         0.
            0.         0.         0.         0.         0.         0.
            0.         0.         0.         1.         1.         1.
            0.8412     0.8412     0.8875     1.484214   0.       ]
          [ 0.3176     0.3176     0.1125     0.        -0.         0.
            0.         0.         0.         0.         0.         0.
            0.         0.         0.         0.         0.         0.
            0.         0.         0.         0.         0.         0.
            0.         0.         0.         0.         0.         0.
            0.         0.         0.         0.         0.         0.
            0.         0.         0.         0.         0.         0.
            0.         0.         0.         0.         0.         0.
            0.         0.         0.         0.         0.         0.
            0.         0.         0.         1.         1.         1.
            0.6824     0.6824     0.8875     1.3111048  0.       ]
          [ 0.4764     0.4764     0.1125     0.        -0.         0.
            0.         0.         0.         0.         0.         0.
            0.         0.         0.         0.         0.         0.
            0.         0.         0.         0.         0.         0.
            0.         0.         0.         0.         0.         0.
            0.         0.         0.         0.         0.         0.
            0.         0.         0.         0.         0.         0.
            0.         0.         0.         0.         0.         0.
            0.         0.         0.         0.         0.         0.
            0.         0.         0.         1.         1.         1.
            0.5236     0.5236     0.8875     1.1558418  0.       ]]]
_last_original_obs:
    value: None
_logger:
    value: <stable_baselines3.common.logger.Logger object at 0x15778f970>
_n_updates:
    value: 0
_num_timesteps_at_start:
    value: 0
_stats_window_size:
    value: 100
_total_timesteps:
    value: 100000
_vec_normalize_env:
    value: None
_wandb:
    value:
        cli_version: 0.19.11
        code_path: code/gym_pybullet_drones/examples/learn_multi.py
        m: []
        python_version: 3.10.5
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 3
                - 13
                - 15
                - 16
                - 22
                - 23
                - 35
                - 55
                - 61
            "4": 3.10.5
            "5": 0.19.11
            "8":
                - 2
                - 5
            "12": 0.19.11
            "13": darwin-arm64
act_type:
    value: PID
action_noise:
    value: None
action_space:
    value: Box(-1.0, 1.0, (4, 3), float32)
algo:
    value: PPO
architecture:
    value: MultiAgent_Matrix
batch_size:
    value: 128
clip_range:
    value: 0.1
clip_range_vf:
    value: None
device:
    value: cpu
duration_sec:
    value: 3
ent_coef:
    value: 0.01
env:
    value: <stable_baselines3.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x135003b80>
ep_info_buffer:
    value: deque([], maxlen=100)
ep_success_buffer:
    value: deque([], maxlen=100)
eval_freq:
    value: 25000
extractor_type:
    value: matrix
features_dim:
    value: 32
gae_lambda:
    value: 0.95
gamma:
    value: 0.99
learning_rate:
    value: 0.0003
log_freq:
    value: 1000
lr_schedule:
    value: <function get_schedule_fn.<locals>.<lambda> at 0x10240e9e0>
max_grad_norm:
    value: 0.5
n_envs:
    value: 1
n_epochs:
    value: 10
n_steps:
    value: 2048
normalize_advantage:
    value: "True"
num_drones:
    value: 4
num_timesteps:
    value: 0
obs_type:
    value: KIN
observation_space:
    value: |-
        Box([[-inf -inf   0. -inf -inf -inf -inf -inf -inf -inf -inf -inf  -1.  -1.
           -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.
           -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.
           -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.
           -1. -inf -inf -inf -inf -inf -inf   0.   0.]
         [-inf -inf   0. -inf -inf -inf -inf -inf -inf -inf -inf -inf  -1.  -1.
           -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.
           -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.
           -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.
           -1. -inf -inf -inf -inf -inf -inf   0.   0.]
         [-inf -inf   0. -inf -inf -inf -inf -inf -inf -inf -inf -inf  -1.  -1.
           -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.
           -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.
           -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.
           -1. -inf -inf -inf -inf -inf -inf   0.   0.]
         [-inf -inf   0. -inf -inf -inf -inf -inf -inf -inf -inf -inf  -1.  -1.
           -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.
           -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.
           -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.
           -1. -inf -inf -inf -inf -inf -inf   0.   0.]], [[inf inf inf inf inf inf inf inf inf inf inf inf  1.  1.  1.  1.  1.  1.
           1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
           1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
           1.  1.  1. inf inf inf inf inf inf 10.  1.]
         [inf inf inf inf inf inf inf inf inf inf inf inf  1.  1.  1.  1.  1.  1.
           1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
           1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
           1.  1.  1. inf inf inf inf inf inf 10.  1.]
         [inf inf inf inf inf inf inf inf inf inf inf inf  1.  1.  1.  1.  1.  1.
           1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
           1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
           1.  1.  1. inf inf inf inf inf inf 10.  1.]
         [inf inf inf inf inf inf inf inf inf inf inf inf  1.  1.  1.  1.  1.  1.
           1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
           1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
           1.  1.  1. inf inf inf inf inf inf 10.  1.]], (4, 65), float32)
policy:
    value: |-
        ActorCriticPolicy(
          (features_extractor): MultiAgentMatrixExtractor(
            (agent_encoder): Sequential(
              (0): Linear(in_features=65, out_features=128, bias=True)
              (1): ReLU()
              (2): LayerNorm((128,), eps=1e-05, elementwise_affine=True)
              (3): Dropout(p=0.1, inplace=False)
              (4): Linear(in_features=128, out_features=128, bias=True)
              (5): ReLU()
              (6): LayerNorm((128,), eps=1e-05, elementwise_affine=True)
              (7): Dropout(p=0.1, inplace=False)
              (8): Linear(in_features=128, out_features=128, bias=True)
              (9): ReLU()
              (10): LayerNorm((128,), eps=1e-05, elementwise_affine=True)
              (11): Linear(in_features=128, out_features=64, bias=True)
              (12): ReLU()
            )
            (aggregator): Sequential(
              (0): Linear(in_features=256, out_features=32, bias=True)
              (1): ReLU()
              (2): LayerNorm((32,), eps=1e-05, elementwise_affine=True)
              (3): Dropout(p=0.1, inplace=False)
              (4): Linear(in_features=32, out_features=32, bias=True)
              (5): ReLU()
            )
          )
          (pi_features_extractor): MultiAgentMatrixExtractor(
            (agent_encoder): Sequential(
              (0): Linear(in_features=65, out_features=128, bias=True)
              (1): ReLU()
              (2): LayerNorm((128,), eps=1e-05, elementwise_affine=True)
              (3): Dropout(p=0.1, inplace=False)
              (4): Linear(in_features=128, out_features=128, bias=True)
              (5): ReLU()
              (6): LayerNorm((128,), eps=1e-05, elementwise_affine=True)
              (7): Dropout(p=0.1, inplace=False)
              (8): Linear(in_features=128, out_features=128, bias=True)
              (9): ReLU()
              (10): LayerNorm((128,), eps=1e-05, elementwise_affine=True)
              (11): Linear(in_features=128, out_features=64, bias=True)
              (12): ReLU()
            )
            (aggregator): Sequential(
              (0): Linear(in_features=256, out_features=32, bias=True)
              (1): ReLU()
              (2): LayerNorm((32,), eps=1e-05, elementwise_affine=True)
              (3): Dropout(p=0.1, inplace=False)
              (4): Linear(in_features=32, out_features=32, bias=True)
              (5): ReLU()
            )
          )
          (vf_features_extractor): MultiAgentMatrixExtractor(
            (agent_encoder): Sequential(
              (0): Linear(in_features=65, out_features=128, bias=True)
              (1): ReLU()
              (2): LayerNorm((128,), eps=1e-05, elementwise_affine=True)
              (3): Dropout(p=0.1, inplace=False)
              (4): Linear(in_features=128, out_features=128, bias=True)
              (5): ReLU()
              (6): LayerNorm((128,), eps=1e-05, elementwise_affine=True)
              (7): Dropout(p=0.1, inplace=False)
              (8): Linear(in_features=128, out_features=128, bias=True)
              (9): ReLU()
              (10): LayerNorm((128,), eps=1e-05, elementwise_affine=True)
              (11): Linear(in_features=128, out_features=64, bias=True)
              (12): ReLU()
            )
            (aggregator): Sequential(
              (0): Linear(in_features=256, out_features=32, bias=True)
              (1): ReLU()
              (2): LayerNorm((32,), eps=1e-05, elementwise_affine=True)
              (3): Dropout(p=0.1, inplace=False)
              (4): Linear(in_features=32, out_features=32, bias=True)
              (5): ReLU()
            )
          )
          (mlp_extractor): MlpExtractor(
            (policy_net): Sequential(
              (0): Linear(in_features=32, out_features=256, bias=True)
              (1): Tanh()
              (2): Linear(in_features=256, out_features=256, bias=True)
              (3): Tanh()
            )
            (value_net): Sequential(
              (0): Linear(in_features=32, out_features=256, bias=True)
              (1): Tanh()
              (2): Linear(in_features=256, out_features=256, bias=True)
              (3): Tanh()
            )
          )
          (action_net): Linear(in_features=256, out_features=12, bias=True)
          (value_net): Linear(in_features=256, out_features=1, bias=True)
        )
policy_class:
    value: <class 'stable_baselines3.common.policies.ActorCriticPolicy'>
policy_kwargs:
    value: '{''features_extractor_class'': <class ''multi_agent_extractors.MultiAgentMatrixExtractor''>, ''features_extractor_kwargs'': {''features_dim'': 32}, ''net_arch'': [{''pi'': [256, 256], ''vf'': [256, 256]}]}'
rollout_buffer:
    value: <stable_baselines3.common.buffers.RolloutBuffer object at 0x135003490>
rollout_buffer_class:
    value: <class 'stable_baselines3.common.buffers.RolloutBuffer'>
rollout_buffer_kwargs:
    value: '{}'
save_freq:
    value: 25000
sde_sample_freq:
    value: -1
seed:
    value: None
start_time:
    value: 1748345533559235000
target_kl:
    value: None
tensorboard_log:
    value: results/multiagent_rpm_matrix_20250527_143211/tb
total_timesteps:
    value: 100000
use_sde:
    value: "False"
verbose:
    value: 1
vf_coef:
    value: 0.5
